<?php

namespace Payment\Adapter\Notification;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-03-12 at 20:17:50.
 */
class PagseguroTest extends \PHPUnit\Framework\TestCase
{

    /**
     * @var Pagseguro
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $conf = array(
            'email' => 'ro.andriotti@gmail.com',
            'token' => '5FB2E8886F634879A56207D4F04C5839',
            'environment' => 'sandbox',
        );

        $this->object = new Pagseguro($conf['environment'], $conf['email'], $conf['token']);
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Payment\Adapter\Notification\Pagseguro::receive
     * @expectedException InvalidArgumentException
     */
    public function testReceiveWithoutParams()
    {
        $response = $this->object->receive();
    }
    
    /**
     * @covers Payment\Adapter\Notification\Pagseguro::receive
     */
    public function testReceiveWithParams()
    {
        $_POST['notificationCode'] = 'teste';
        $_POST['notificationType'] = 'teste';
        
        $response = $this->object->receive();
    }

}
