<?php

namespace Payment\Adapter\Notification;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-03-12 at 20:17:50.
 */
class PagseguroTest extends \PHPUnit\Framework\TestCase
{

    /**
     * @var Pagseguro
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $conf = require getcwd() . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'config_file.php';

        $this->object = new Pagseguro($conf['pagseguro_environment'], $conf['pagseguro_email'], $conf['pagseguro_token']);
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Payment\Adapter\Notification\Pagseguro::receive
     * @expectedException InvalidArgumentException
     */
    public function testReceiveWithoutParams()
    {
        $response = $this->object->receive();
    }
    
    /**
     * @covers Payment\Adapter\Notification\Pagseguro::receive
     */
    public function testReceiveWithParams()
    {
        $_POST['notificationCode'] = '3FD8CD9964BE64BEDDA8846E0FA12752002E';
        $_POST['notificationType'] = 'transaction';
        
        $response = $this->object->receive();
    }

}
